namespace FileExplorer.Services;

public static class ThemeColorDefaults
{
    public static IReadOnlyDictionary<string, string> Dark { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["GlassBackgroundBrush"] = "#B3121212",
        ["PanelBackgroundBrush"] = "#66181818",
        ["ModalPanelBackgroundBrush"] = "#FF141414",
        ["BorderBrushDark"] = "#33FFFFFF",
        ["TextPrimaryBrush"] = "#F0F0F0",
        ["TextSecondaryBrush"] = "#B0B0B0",
        ["AccentBrush"] = "#4DA3FF",
        ["HoverBrush"] = "#18FFFFFF",
        ["SelectionFillBrush"] = "#330078D7",
        ["SelectionFillHoverBrush"] = "#440078D7",
        ["SelectionFillInactiveBrush"] = "#220078D7",
        ["SelectionBorderBrush"] = "#0078D7",
        ["SelectionBorderInactiveBrush"] = "#660078D7",
        ["SelectionForegroundBrush"] = "#FFFFFF",
        ["SelectedBrush"] = "#330078D7",
        ["AddressBarBackgroundBrush"] = "#44000000",
        ["AppControlBackground"] = "#44000000",
        ["AppTextForeground"] = "#F0F0F0",
        ["AppControlBorderBrush"] = "#33FFFFFF",
        ["AppControlHoverBackground"] = "#18FFFFFF",
        ["AppControlPressedBackground"] = "#2AFFFFFF",
        ["AppPopupBackground"] = "#F0181818",
        ["AppPopupBorderBrush"] = "#33FFFFFF",
        ["OpaqueInputBackgroundBrush"] = "#FF1A1A1A",
        ["CloseHoverBrush"] = "#E81123",
        ["DimOverlayBrush"] = "#A6000000",
        ["TitleBarBackgroundBrush"] = "#33000000",
        ["OverlayHeaderBrush"] = "#44000000",
        ["ButtonChromeBrush"] = "#33000000",
        ["ButtonPressedBrush"] = "#45FFFFFF",
        ["DialogButtonBrush"] = "#2AFFFFFF",
        ["DialogButtonHoverBrush"] = "#45FFFFFF",
        ["DialogDangerBrush"] = "#55E81123",
        ["DialogDangerHoverBrush"] = "#88E81123",
        ["DialogDangerPressedBrush"] = "#C50F1F",
        ["ContextMenuBackgroundBrush"] = "#F0181818",
        ["SeparatorBrush"] = "#33FFFFFF",
        ["ColumnHeaderBackgroundBrush"] = "#22000000",
        ["ScrollBarThumbBrush"] = "#55FFFFFF",
        ["EditorBackgroundBrush"] = "#33000000",
        ["StatusBarBackgroundBrush"] = "#22000000",
        ["ErrorTextBrush"] = "#FFFF6B6B",
        ["PaneInactiveBorderBrush"] = "#33FFFFFF",
        ["SplitterIdleBrush"] = "#18000000",
        ["SplitterHoverBrush"] = "#550078D7",
        ["ShadowColor"] = "#FF000000",
        ["GitModifiedBrush"] = "#E2C08D",
        ["GitAddedBrush"] = "#73C991",
        ["GitDeletedBrush"] = "#F44747",
        ["GitUntrackedBrush"] = "#73C991",
        ["GitIgnoredBrush"] = "#666666",
        ["GitConflictBrush"] = "#FF9D00",
        ["TransparentFillColor"] = "#00000000",
        ["HoverFillColor"] = "#18FFFFFF",
        ["SelectionFillColor"] = "#330078D7",
        ["SelectionFillHoverColor"] = "#440078D7",
        ["SelectionBorderColor"] = "#0078D7"
    };
}
